[package]
name = "merge_it"
version = "0.1.0"
authors = ["williambright"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
